In [2]:
import pandas as pd
df = pd.read_csv("D:/Courses/Codebasics Python/Python Projects and Exercises/ML/14_naive_bayes/titanic.csv")
df.head()

PassengerId                                               Name  Pclass  \
0            1                            Braund, Mr. Owen Harris       3   
1            2  Cumings, Mrs. John Bradley (Florence Briggs Th...       1   
2            3                             Heikkinen, Miss. Laina       3   
3            4       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1   
4            5                           Allen, Mr. William Henry       3   

      Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  \
0    male  22.0      1      0         A/5 21171   7.2500   NaN        S   
1  female  38.0      1      0          PC 17599  71.2833   C85        C   
2  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S   
3  female  35.0      1      0            113803  53.1000  C123        S   
4    male  35.0      0      0            373450   8.0500   NaN        S   

   Survived  
0         0  
1         1  
2         1  
3         1  
4         0

In [4]:
df.drop(['PassengerId', 'Name', 'SibSp', 'Parch', 'Ticket', 'Cabin', 'Embarked'], axis = 'columns', inplace = True)

In [9]:
target = df.Survived
inputs = df.drop('Survived', axis = 'columns')

In [10]:
dummies = pd.get_dummies(inputs.Sex)
dummies.head(3)

female  male
0       0     1
1       1     0
2       1     0

In [12]:
inputs = pd.concat([inputs, dummies], axis = 'columns')
inputs.head(3)

Pclass     Sex   Age     Fare  female  male
0       3    male  22.0   7.2500       0     1
1       1  female  38.0  71.2833       1     0
2       3  female  26.0   7.9250       1     0

In [13]:
inputs.drop('Sex', axis = 'columns', inplace = True)
inputs.head(3)

Pclass   Age     Fare  female  male
0       3  22.0   7.2500       0     1
1       1  38.0  71.2833       1     0
2       3  26.0   7.9250       1     0

In [14]:
inputs.columns[inputs.isna().any()]

Index(['Age'], dtype='object')

In [15]:
inputs.Age = inputs.Age.fillna(inputs.Age.mean())

In [17]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(inputs, target)

In [19]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [20]:
model.fit(x_train, y_train)

GaussianNB()

In [21]:
model.score(x_test, y_test) 

0.8071748878923767

In [23]:
 x_test[:10]

Pclass        Age      Fare  female  male
524       3  29.699118    7.2292       0     1
568       3  29.699118    7.2292       0     1
299       1  50.000000  247.5208       1     0
806       1  39.000000    0.0000       0     1
737       1  35.000000  512.3292       0     1
44        3  19.000000    7.8792       1     0
666       2  25.000000   13.0000       0     1
808       2  39.000000   13.0000       0     1
105       3  28.000000    7.8958       0     1
108       3  38.000000    7.8958       0     1

In [25]:
y_test[:10]

524    0
568    0
299    1
806    0
737    1
44     1
666    0
808    0
105    0
108    0
Name: Survived, dtype: int64

In [26]:
model.predict(x_test[:10])

array([0, 0, 1, 0, 1, 1, 0, 0, 0, 0], dtype=int64)

In [27]:
 model.predict_proba(x_test[:10])

array([[9.88107794e-01, 1.18922061e-02],
       [9.88107794e-01, 1.18922061e-02],
       [4.02439002e-10, 1.00000000e+00],
       [8.97221150e-01, 1.02778850e-01],
       [2.58714880e-32, 1.00000000e+00],
       [5.15380646e-02, 9.48461935e-01],
       [9.71526412e-01, 2.84735881e-02],
       [9.73586073e-01, 2.64139265e-02],
       [9.87941567e-01, 1.20584330e-02],
       [9.88439134e-01, 1.15608662e-02]])

## To fix number format issues in output like the one above:

In [31]:
import numpy as np
np.set_printoptions(precision=4, suppress = True) 

In [32]:
model.predict_proba(x_test[:10])

array([[0.9881, 0.0119],
       [0.9881, 0.0119],
       [0.    , 1.    ],
       [0.8972, 0.1028],
       [0.    , 1.    ],
       [0.0515, 0.9485],
       [0.9715, 0.0285],
       [0.9736, 0.0264],
       [0.9879, 0.0121],
       [0.9884, 0.0116]])